os: linux

before_install:
  - sudo apt-get update -y
  
language: node_js

node_js:
  - "node"

cache: npm

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  keep_history: true
  on:
    tags: true

deploy:
  provider: npm
  email: "667@june07.com"
  api_key: "$NPM_TOKEN"
